
version: '3'

services:
    php_service:
        image: php:7-fpm
        volumes:
            - ./code:/code
        # What to name the container
        container_name: php_service_container
        restart: always
    nginx:
        build: nginx/
        image: nginx_rev-proxy_image
        volumes:
            - ./code:/code
        container_name: nginx_rev-proxy_container
        # Wait for php_service before starting
        depends_on:
            - php_service
        # What ports to open
        ports:
            - "80:80"
        restart: always
        # Allow nginx service to talk to php_service
        links:
            - php_service
