
version: '3'

services:
    node_service:
        # Where to build from
        build: server/
        # What to name the image
        # If build key not present, looks for image "node_image"
        image: node_image
        # What to name the container
        container_name: node_service_container
        restart: always
    nginx:
        build: nginx/
        image: nginx_rev-proxy_image
        container_name: nginx_rev-proxy_container
        # Wait for node_service before starting
        depends_on:
            - node_service
        # What ports to open
        ports:
            - "80:80"
        restart: always
        # Allow nginx service to talk to node_service
        links:
            - node_service
